#!/bin/bash
 
#
# A sample Giddyup 'start' hook.
# This is run *after* the current release has been changed.
#

echo "start hook execution beginning"

# Source giddyup functions
. /usr/local/lib/giddyup/functions.sh

# Anchor server-specific config
. shared/config/hooks/appserver_config

# Use RVM
. /home/${USERDIR}/.rvm/environments/default

# Ensure that bundle is shared
share vendor/bundle

# Symlinks configuration files from shared/path to current/path
share config/database.yml
share config/newrelic.yml
share config/initializers/secret_token.rb

# Symlink any shared static html files
share public/test

# Configure bundler to deal with PostgreSQL properly, then deploy the new bundle.
cd "${RELEASE}"
BUNDLE_BUILD__PG="--with-pg-config=/usr/pgsql-9.1/bin/pg_config" bundle install --deployment

# Precompile assets. guard requires $HOME to be defined.
export HOME=${RELEASE}
bundle exec rake --trace assets:precompile RAILS_ENV="${RAILS_ENV}"

# DB migration
bundle exec rake db:migrate RAILS_ENV="${RAILS_ENV}"
cd "${ROOT}"

# Start app server
sudo /usr/local/bin/allah start "${APPSERVER}"

# Start the background worker
sudo /usr/local/bin/allah start "${BACKGROUND_WORKER}"

# Disable maintenance page
# Uncomment these if you wish to use a maintenance page
#cd "${RELEASE}"
#mv public/system/maintenance.html public/system/maintenance.html.disabled

echo "start hook execution completed"