#! /bin/bash

#
# This is a sample Giddyup 'stop' hook script. It is run on the *old* release.
#

# Source giddyup functions
. /usr/local/lib/giddyup/functions.sh

# Enable maintenance page
# Uncomment these if you wish to use a maintenance page
#cd "${RELEASE}"
#mv public/system/maintenance.html.disabled public/system/maintenance.html || true

# Anchor config - defines vars below
. shared/config/hooks/appserver_config

# Stop background job worker
sudo /usr/local/bin/allah stop "${APPSERVER}"

# Stop app server
sudo /usr/local/bin/allah stop "${BACKGROUND_WORKER}"
